### ISSUE TITLE
Switch from norch-bootstrap to norch-angular-app to keep up with features

### ISSUE THREAD

**Issue by eklem** [eklem/life-index#16]
Seems it's time to switch from [norch-bootstrap](https://github.com/fergiemcdowall/norch-bootstrap) to [norch-angular-app](https://github.com/fergiemcdowall/norch-angular-app). `norch-bootstrap` is a bit limiting, and all the fun, new features and maintenance of old features is happening over at `norch-angular-app`.

A little unsure if I should use norch-angular-app or something simpler. I need to get a single-page-app that will work with browserify in the end.

**Comment by fergiemcdowall** [comment]
Norch-bootstrap is definitely out

The angular app is also bit of a monster, although its a nicely organised monster with tests and bower.

I wonder if something based on react + browserify is the way forward..? I like the idea of going npm all the way for package management in the browser, and react seems to be lighter than angular, yet still has sufficient functionality.

But yes, definitely norch-angular-app instead of norch-bootstrap :)

**Comment by eklem** [comment]
Thanks. I'll test `norch-angular-app` quickly and then look into react + browserify. We need a lightweight solution that will work "out of the box" and have most of the shiny features =)

**Comment by eklem** [comment]
And life-index needs something that can run in the browser.

**Comment by eklem** [comment]
And it's working!
